image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - build
  - deploy

docker-build:
  # Use the official docker image.
  stage: build
  script:
    - 'eval "uname -a"'
    - 'eval "cat /etc/os-release"'
    - docker version
    - docker build -t projetIb:v1 .