image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:          # List of stages for jobs, and their order of execution
  - build
  #- scan
  - test-acceptation
  - test
  - push
  - deploy
  - test-deploy
  - monitor

build: # Construction de l'image avec Dockerfile
  stage: build
  script:
    - echo "Construction de l'image avec Dockerfile"
    - docker build -t imagedevopsapp .
    - docker save imagedevopsapp > imagedevopsapp.tar
  artifacts:
    paths:
    - imagedevopsapp.tar   

#scan:   # scan de l'image via docker-scan 
#  stage: scan
#  script:
#    - echo "via docker-scan"
#    - cat /etc/os-release
#    - apk add docker-scan-plugin
#    - docker scan imagedevopsapp

test acceptation: # Controle l'intégrité du conteneur et app   
  stage: test-acceptation
  script:
    - docker load < imagedevopsapp.tar
    - docker run --rm imagedevopsapp cat /usr/share/nginx/html/index.html | grep Start CSS
    - sleep 5  

test:   # Test de l'appli MochaJS
  stage: test
  script:
    - echo "Test unitaire MochaJS"

push :   # via docker run et curl
  stage: push
  script:
    - echo "push de limage sur docker hub"

deploy: # Ansible via playbook 
  stage: deploy 
  script:
    - echo "Ansible via playbook"

test-deploy:
  stage: test-deploy 
  script:
    - echo "curl sur http ??"

monitor:
  stage: monitor 
  script:
    - echo "monitoring prometheus -> grafana"