image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - build
  - deploy

docker-build:
  # Use the official docker image.
  stage: build
  script:
    - docker build -t projetgr3:v1 .
