image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:          # List of stages for jobs, and their order of execution
  - build
  #- scan
  - test-acceptation
  - test-application
  - release-image
  - deploy-staging
  - test-deploy-staging
  - monitor

build: # Construction de l'image avec Dockerfile
  stage: build
  script:
    - echo "Construction de l'image avec Dockerfile"
    - docker build -t imagedevopsapp .
    - docker save imagedevopsapp > imagedevopsapp.tar
  artifacts:
    paths:
    - imagedevopsapp.tar   

#scan:   # scan de l'image via docker-scan 
#  stage: scan
#  script:
#    - echo "via docker-scan"
#    - cat /etc/os-release
#    - apk add docker-scan-plugin
#    - docker scan imagedevopsapp

test acceptation: # Controle l'intégrité du conteneur et app   
  stage: test-acceptation
  script:
    - docker load < imagedevopsapp.tar
    - docker run -d -p 80:80 -e PORT=80 --name webapp imagedevopsapp
    - sleep 5
    - apk --no-cache add curl
    - curl -I "http://docker"

test application:   # Test de l'appli MochaJS
  stage: test-application
  script:
    - echo "Test unitaire MochaJS"

release-image:  # Dépot de l'image sur Dockerhub
  stage: release-image
  script:
    - docker load < imagedevopsapp.tar
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD" 
    - docker tag imagedevopsapp:latest bidou974/imagedevopsapp:latest
    - docker push bidou974/imagedevopsapp:latest

deploy-staging: # Déploiement staging sur Heroku 
  stage: deploy-staging
  environment:
    name: staging
    url: https://devopsapp-staging.herokuapp.com
  only:
    - main
  script:
    - docker load < imagedevopsapp.tar
    - docker image
    - docker run -d --name devopsapp-staging imagedevopsapp
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku container:rm -a devopsapp-staging web
    - heroku create devopsapp-staging || echo "project already exist"
    - heroku container:push -a devopsapp-staging web
    - heroku container:release -a devopsapp-staging web

test-deploy-staging: # Test du déploiement staging sur Heroku 
  stage: test-deploy-staging
  script:
    - echo "test deploy"
    - apk --no-cache add curl
    - curl "https://devopsapp-staging.herokuapp.com" | grep "Start" 

monitor:
  stage: monitor 
  script:
    - echo "monitoring prometheus -> grafana"
    