image: docker:latest
services:
  - name: docker:dind
    alias: docker
    
stages:
- test

docker:test:
  stage: test
  tags:
    - docker
  before_script:
    - apt-get install docker -y
    - docker --version
  script:
    - docker ps