image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:          # List of stages for jobs, and their order of execution
  - build
  #- scan
  - test-acceptation
  - test-application
  - push
  - deploy-staging
  - test-deploy
  - monitor

build: # Construction de l'image avec Dockerfile
  stage: build
  script:
    - echo "Construction de l'image avec Dockerfile"
    - docker build -t imagedevopsapp .
    - docker save imagedevopsapp > imagedevopsapp.tar
  artifacts:
    paths:
    - imagedevopsapp.tar   

#scan:   # scan de l'image via docker-scan 
#  stage: scan
#  script:
#    - echo "via docker-scan"
#    - cat /etc/os-release
#    - apk add docker-scan-plugin
#    - docker scan imagedevopsapp

test acceptation: # Controle l'intégrité du conteneur et app   
  stage: test-acceptation
  script:
    - docker load < imagedevopsapp.tar
    #- docker run --rm imagedevopsapp cat /usr/share/nginx/html/index.html | grep Start
    - docker run -d -p 8080:80 --name devopsapp-staging imagedevopsapp
    - curl locahost:8080
    - sleep 5  

test application:   # Test de l'appli MochaJS
  stage: test-application
  script:
    - echo "Test unitaire MochaJS"

push :   # via docker run et curl
  stage: push
  script:
    - echo "push de limage sur docker hub"

deploy-staging: 
  stage: deploy-staging
  environment:
    name: staging
    url: https://devopsapp-staging.herokuapp.com
  only:
    - main
  script:
    - docker load < imagedevopsapp.tar
    - docker run -d --name devopsapp-staging imagedevopsapp
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku container:rm -a devopsapp-staging web
    - heroku create devopsapp-staging || echo "project already exist"
    - heroku container:push -a devopsapp-staging web
    - heroku container:release -a devopsapp-staging web

test-deploy: 
  stage: test-deploy
  script:
    - echo "test deploy"
    - apk --no-cache add curl
    - curl "https://devopsapp-staging.herokuapp.com" | grep "Start" 

monitor:
  stage: monitor 
  script:
    - echo "monitoring prometheus -> grafana"
    